# Generated by Django 5.2.16 on 2026-08-02 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_title', models.CharField(max_length=200)),
                ('bring_own_game', models.BooleanField(default=True)),
                ('game_language', models.CharField(choices=[('en', 'English'), ('de', 'German'), ('other', 'Other')], default='en', max_length=8)),
                ('game_language_other', models.CharField(blank=True, max_length=100)),
                ('venue_game_confirmed', models.BooleanField(default=False)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('min_players', models.PositiveIntegerField(default=2)),
                ('max_players', models.PositiveIntegerField(default=4)),
                ('status', models.CharField(choices=[('waiting_for_venue_confirmation', 'Waiting for venue confirmation'), ('waiting_for_players', 'Waiting for players'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='waiting_for_venue_confirmation', max_length=40)),
                ('seats_taken', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_tables', to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='venues.venue')),
            ],
        ),
        migrations.CreateModel(
            name='SeatReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_organizer', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('waitlisted', 'Waitlisted'), ('cancelled', 'Cancelled')], default='reserved', max_length=16)),
                ('waitlist_position', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_reservations', to=settings.AUTH_USER_MODEL)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='tables.table')),
            ],
        ),
        migrations.CreateModel(
            name='LateCancellationMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='late_cancellation_marks', to=settings.AUTH_USER_MODEL)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='late_cancellation_marks', to='tables.table')),
            ],
        ),
        migrations.AddIndex(
            model_name='table',
            index=models.Index(fields=['venue', 'starts_at'], name='tables_tabl_venue_i_2b8fab_idx'),
        ),
        migrations.AddIndex(
            model_name='table',
            index=models.Index(fields=['status', 'starts_at'], name='tables_tabl_status_216b34_idx'),
        ),
        migrations.AddIndex(
            model_name='seatreservation',
            index=models.Index(fields=['table', 'status'], name='tables_seat_table_i_a1b2e8_idx'),
        ),
        migrations.AddIndex(
            model_name='seatreservation',
            index=models.Index(fields=['user', 'status'], name='tables_seat_user_id_6c4992_idx'),
        ),
        migrations.AddConstraint(
            model_name='seatreservation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'reserved')), fields=('table', 'user'), name='uniq_active_seat_per_user_per_table'),
        ),
    ]
