# Generated by Django 5.2.16 on 2026-08-06 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='host_comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
