# Generated by Django 5.2.16 on 2026-08-04 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bggresolution',
            name='thumbnail_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
