# Generated by Django 5.2.16 on 2026-08-06 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgg', '0002_bggresolution_thumbnail_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bggresolution',
            name='bgg_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
