"""Curated list of popular BoardGameGeek *main* titles (base games only).

BGG's live search API requires an approved token (see services.py), so this is a
static, hand-curated set of well-known base games — no expansions or alternate
editions ("versions"). It backs the game dropdown when creating a table and can be
swapped for a live BGG query once a token is configured.
"""

MAIN_TITLES: list[str] = [
    "7 Wonders",
    "7 Wonders Duel",
    "Agricola",
    "Arkham Horror",
    "Ark Nova",
    "Azul",
    "Barrage",
    "Betrayal at House on the Hill",
    "Blood Rage",
    "Brass: Birmingham",
    "Brass: Lancashire",
    "Calico",
    "Camel Up",
    "Cascadia",
    "Catan",
    "Carcassonne",
    "Caverna",
    "Champions of Midgard",
    "Clank!",
    "Codenames",
    "Concordia",
    "Cosmic Encounter",
    "Coup",
    "Dead of Winter",
    "Dixit",
    "Dominion",
    "Dune: Imperium",
    "Eldritch Horror",
    "Everdell",
    "Exploding Kittens",
    "Five Tribes",
    "Food Chain Magnate",
    "Forbidden Island",
    "Gaia Project",
    "Ghost Stories",
    "Gloomhaven",
    "Great Western Trail",
    "Hansa Teutonica",
    "Hive",
    "Innovation",
    "Isle of Skye",
    "Istanbul",
    "Jaipur",
    "Kingdomino",
    "King of Tokyo",
    "Lisboa",
    "Lords of Waterdeep",
    "Lost Ruins of Arnak",
    "Love Letter",
    "Mansions of Madness",
    "Marvel Champions",
    "Mysterium",
    "Nemesis",
    "Newton",
    "Obsession",
    "On Mars",
    "Orleans",
    "Pandemic",
    "Pandemic Legacy: Season 1",
    "Paladins of the West Kingdom",
    "Patchwork",
    "Photosynthesis",
    "Power Grid",
    "Puerto Rico",
    "Raiders of the North Sea",
    "Res Arcana",
    "Root",
    "Santorini",
    "Scythe",
    "Spirit Island",
    "Splendor",
    "Star Wars: Rebellion",
    "Stone Age",
    "Sushi Go!",
    "Suburbia",
    "Takenoko",
    "Terra Mystica",
    "Terraforming Mars",
    "The Castles of Burgundy",
    "The Crew: The Quest for Planet Nine",
    "The Mind",
    "The Quacks of Quedlinburg",
    "The Resistance",
    "Ticket to Ride",
    "Tigris & Euphrates",
    "Tzolk'in: The Mayan Calendar",
    "Twilight Imperium",
    "Twilight Struggle",
    "Underwater Cities",
    "Viticulture",
    "Welcome To",
    "Wingspan",
    "Yahtzee",
    "Zombicide",
]
