# Generated by Django 5.2.16 on 2026-08-02 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VenueAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('tables_available', models.PositiveIntegerField(default=1)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='venues.venue')),
            ],
            options={
                'indexes': [models.Index(fields=['venue', 'date'], name='venues_venu_venue_i_84c3b5_idx')],
            },
        ),
    ]
