# Generated by Django 5.2.16 on 2026-08-11 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='max_players',
            field=models.PositiveIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='venue',
            name='min_players',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
