# Generated by Django 5.2.16 on 2026-08-11 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0003_seed_date_house_cafe'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='venues.venue')),
            ],
            options={
                'ordering': ['title'],
                'constraints': [models.UniqueConstraint(fields=('venue', 'title'), name='uniq_venue_game_title')],
            },
        ),
    ]
