# Generated by Django 5.2.16 on 2026-08-11 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0004_refresh_date_house_hours'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venue_closures_created', to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closures', to='venues.venue')),
            ],
            options={
                'ordering': ['date'],
                'constraints': [models.UniqueConstraint(fields=('venue', 'date'), name='uniq_venue_closure_date')],
            },
        ),
        migrations.CreateModel(
            name='VenueWeeklyHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField()),
                ('is_closed', models.BooleanField(default=False)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_hours', to='venues.venue')),
            ],
            options={
                'ordering': ['weekday'],
                'constraints': [models.UniqueConstraint(fields=('venue', 'weekday'), name='uniq_venue_weekday_hours'), models.CheckConstraint(condition=models.Q(('weekday__gte', 0), ('weekday__lte', 6)), name='venue_weekday_0_6')],
            },
        ),
    ]
