# Generated by Django 5.2.16 on 2026-08-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0006_seed_weekly_hours_date_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='max_reservation_minutes',
            field=models.PositiveIntegerField(default=180),
        ),
        migrations.AddField(
            model_name='venue',
            name='min_reservation_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
