# Generated by Django 5.2.16 on 2026-08-11 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0007_venue_reservation_duration_limits'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('bgg_id', models.PositiveIntegerField(blank=True, null=True)),
                ('thumbnail_url', models.URLField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='venues.venue')),
            ],
            options={
                'ordering': ['title'],
                'constraints': [models.UniqueConstraint(fields=('venue', 'title'), name='uniq_venue_game_title'), models.UniqueConstraint(condition=models.Q(('bgg_id__isnull', False)), fields=('venue', 'bgg_id'), name='uniq_venue_game_bgg_id')],
            },
        ),
    ]
