# Generated by Django 5.2.16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("venues", "0017_venue_create_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="venuegame",
            name="maintenance_note",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="venuegame",
            name="maintenance_requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="venuegame",
            name="maintenance_requested_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="venue_game_maintenance_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="venuegame",
            name="needs_maintenance",
            field=models.BooleanField(default=False),
        ),
    ]
