# Generated by Django 5.2

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("venues", "0017_venuegame_seat_limits"),
    ]

    operations = [
        migrations.CreateModel(
            name="VenuePhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("image", models.FileField(upload_to="venue_photos/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "venue",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_photo",
                        to="venues.venue",
                    ),
                ),
            ],
        ),
    ]
