from django.urls import path

from .views import (
    ChangePasswordView,
    ChatListView,
    ChatThreadView,
    FavoriteCategoriesView,
    FriendListView,
    FriendRequestAcceptView,
    FriendRequestListView,
    FriendRequestRejectView,
    GoogleConfigView,
    GoogleLoginView,
    LoginView,
    MeView,
    PublicUserGamesView,
    PublicUserView,
    RegisterView,
    RollAvatarView,
    UserSearchView,
)

urlpatterns = [
    path("auth/register", RegisterView.as_view(), name="register"),
    path("auth/login", LoginView.as_view(), name="login"),
    path("auth/google", GoogleLoginView.as_view(), name="google-login"),
    path("auth/google/config", GoogleConfigView.as_view(), name="google-config"),
    path("auth/me", MeView.as_view(), name="me"),
    path("me/avatar/roll", RollAvatarView.as_view(), name="roll-avatar"),
    path("me/favorite-categories", FavoriteCategoriesView.as_view(), name="favorite-categories"),
    path("me/password", ChangePasswordView.as_view(), name="change-password"),
    path("users", UserSearchView.as_view(), name="user-search"),
    path("users/<int:pk>/games", PublicUserGamesView.as_view(), name="public-user-games"),
    path("users/<int:pk>", PublicUserView.as_view(), name="public-user"),
    path("friends/requests/<int:pk>/accept", FriendRequestAcceptView.as_view(), name="friend-accept"),
    path("friends/requests/<int:pk>/reject", FriendRequestRejectView.as_view(), name="friend-reject"),
    path("friends/requests", FriendRequestListView.as_view(), name="friend-requests"),
    path("friends", FriendListView.as_view(), name="friends"),
    path("chats/<int:pk>", ChatThreadView.as_view(), name="chat-thread"),
    path("chats", ChatListView.as_view(), name="chats"),
]
