# Generated by Django 5.2.16 on 2026-08-06 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_seed',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
