# Generated by Django 5.2.16 on 2026-08-19 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_directmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="favorite_categories",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
