# Generated by Django 5.2.16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_user_favorite_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar_unlocks",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="user",
            name="avatar_equipped",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
