# Generated by Django 5.2.16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="friendship",
            name="rejected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
