# Generated by Django 5.2.16 on 2026-08-03 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tables.table'),
        ),
    ]
