# Generated by Django 5.2.16

from django.db import migrations, models


def truncate_review_bodies(apps, schema_editor):
    Review = apps.get_model("reviews", "Review")
    for review in Review.objects.exclude(body="").iterator():
        if len(review.body) > 50:
            review.body = review.body[:50]
            review.save(update_fields=["body"])


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_review_table"),
    ]

    operations = [
        migrations.RunPython(truncate_review_bodies, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="review",
            name="body",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
